//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employee {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.TextBox txtv1;
        
        protected System.Web.UI.WebControls.Button Button1;
        
        protected System.Web.UI.WebControls.Label err;
        
        protected System.Web.UI.WebControls.Button Button2;
        
        protected System.Web.UI.WebControls.PlaceHolder placeholder1;
        
        protected System.Web.UI.WebControls.TextBox txtv2;
        
        protected System.Web.UI.WebControls.Button Button3;
        
        protected System.Web.UI.WebControls.Label label2;
        
        protected System.Web.UI.WebControls.Label label3;
        
        protected System.Web.UI.WebControls.TextBox txtv3;
        
        protected System.Web.UI.WebControls.Label label4;
        
        protected System.Web.UI.WebControls.TextBox txtv4;
        
        protected System.Web.UI.WebControls.Button Button4;
        
        protected System.Web.UI.WebControls.Label label5;
    }
}
